# Generated by Django 3.0.5 on 2020-09-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin'), (4, 'admin_django')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
