# Generated by Django 3.0.5 on 2020-09-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200926_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
